# CV
## {{< iconify octicon:mortar-board-24 >}} Teaching

I have developed class tutorial workflows covering archiving and building upon corpora from digitized written and spoken material. Much earlier (~2001) I was leading a kids computer workshop where we built an online hyperlink book (sic! 2001...) and generally was assisting handicapped or not kids to learning or simply having a good time... 

## {{< iconify octicon:tools-24 >}} Technical Skills {.interests}

- content management (wordpress, github frameworks)
- layout / editorial work (quark express, quarto, rmarkdown)
- TEI conventional corpus building oral/written sources (dracor, C.W. Pfaff archiving assistant)
- correctorat
- R
- bit of Rust/Python
- (gpt assisted) iOS/Mac app development
- basic server administration
- french+, russian- / hebrew- language


## {{< iconify octicon:star-24 >}} Interests {.interests}

- corpus linguistics
- discourse analysis
- structural grammar theories
- archiving
- data analysis & visualisation, QDA
- reproducible / open source research
- distant reading approaches to literature
  - but also really reading... 
- general: computational linguistics and DH

## {{< iconify octicon:mortar-board-24 >}} Education {.education}

- **Studium** (*Linguistik, Komparatistik; B.A.*), **2025-**  
  *FUB*

- **Studium** (*Linguistik, Komparatistik, Hebräisch; B.A.*), **2023-2025**  
  *FUB*

- **Studium** (*Linguistik, Komparatistik, Informatik; B.A.*), **2019-2023**  
  *FUB*

- **Gärtnermeister** (*Friedhofsgartenbau*), **2018**  

- **Ausbildung** (*Zierpflanzenbau*), **2005-2008**  

- **Studium** (*Politikwissenschaften, Psychologie, Erziehungswissenschaften; M.A.*), **2000-2003**  
  *Fernuniversität in Hagen*

- **Studium** (*Germanistik, Politikwissenschaften; Lehramt*), **1998-2000**  
  *FUB*


